### PR TITLE
Debug struct

### PR DESCRIPTION
**Pull request by BitsAndDroids**
- I added the debug trait to the Simconnector structure. This makes it easier to add the struct to other debuggable structs
- upped version in readme since it was out of sync
- added shield always to reflect the latest version in the Readme
- added an example to demonstrate user input handling

### CODE REVIEW

**Comment by BitsAndDroids** [comment]
Hi @Sequal32, I've added a new example of how to handle sim connect inputs. Plus fixed the version in the README

**Comment by Sequal32** [comment]
Thanks for this and it looks great! Before this can be merged just ensure your new example is linted with `cargo clippy` and formatted with `cargo fmt`.

**Comment by BitsAndDroids** [comment]
@Sequal32 I've run the format and clippy. To make myself and others remember in the future, I've added a PR template.

**Comment by Sequal32** [comment]
Awesome looks great. Thanks!

**Pull request merged**
